version: 2.1
jobs:
  test:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: clippy
          command: |
            rustup component add clippy
            cargo clippy -- -D warnings
      - run:
          name: fmt
          command: cargo fmt -- --check
      - run:
          name: test
          command: cargo test --features mock
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: build
          command: cargo build
      - store_artifacts:
          path: "target/debug/photo-album"

workflows:
  version: 2
  workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
