version: 2.1
jobs:
  validate:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: clippy
          command: |
            rustup component add clippy
            cargo clippy -- -D warnings
      - run:
          name: fmt
          command: cargo fmt -- --check
      - run:
          name: test
          command: cargo test
